# Generated by Django 4.0.6 on 2022-08-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['word']},
        ),
    ]
