# Generated by Django 4.0.6 on 2022-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='author',
            field=models.CharField(default='Unknown author', max_length=64),
        ),
        migrations.AlterField(
            model_name='example',
            name='source',
            field=models.CharField(default='unknown source', max_length=128),
        ),
    ]
