# Generated by Django 4.0.6 on 2022-08-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_entry_personal_dictionaries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylearningprogress',
            name='personal_dictionaries',
        ),
        migrations.AddField(
            model_name='entrylearningprogress',
            name='personal_dictionary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elp', to='dictionary.personaldictionary'),
        ),
        migrations.AlterField(
            model_name='entrylearningprogress',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.entry'),
        ),
    ]
