# Generated by Django 4.0.6 on 2022-08-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_remove_entrylearningprogress_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dictionary.tag'),
        ),
    ]
