# Generated by Django 4.0.6 on 2022-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_remove_tag_entry_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='antonyms',
            field=models.ManyToManyField(related_name='ant', to='dictionary.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='synonyms',
            field=models.ManyToManyField(related_name='syn', to='dictionary.entry'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
