# Generated by Django 4.1 on 2022-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_alter_tag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='ant', to='dictionary.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='syn', to='dictionary.entry'),
        ),
    ]
