# Generated by Django 4.1 on 2022-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_alter_entry_antonyms_alter_entry_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
